name=input('请输入您的姓名:')
hoppy=input('请输入您的爱好:')
print('您输入的姓名为:'+name+'，您的爱好为:'+hoppy)
print('您输入的姓名为:',name,'，您的爱好为:',hoppy)
print('您输入的姓名为:%s，您的爱好为:%s'%(name,hoppy))
print('您输入的姓名为:%s'%name)
print('您的爱好为:%s'%hoppy)
